trigger: none
# Uncomment the below section if you want to schedule your pipeline
# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily midnight build
#   branches:
#     include:
#     - master
#   always: true
pool: Default
#  vmImage: Ubuntu-16.04

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# TODO : Add the variables needed in your configuration file below
  # Required variables
  # ==================
  # configuration file to use
  azhpc.config: azurehpc/examples/simple_hpc_pbs/config.json
  azhpc.pipeline_dir: examples/simple_hpc_pbs
  azhpc.hpc_image: OpenLogic:CentOS-HPC:7.6:latest
  azhpc.location: westeurope
  azhpc.vm_type: Standard_HC44rs
  azhpc.compute_instances: 4
  # To enable multiple configurations to be run in parallel, store all your configs into a json file and comment out the line below
  #azhpc.variables_matrix: healthcheck/matrix.json

  # Optional variables
  # ==================
  # If branch is not specified the master branch if azhpc will be checked out
  #azhpc.branch: telemetry
  # uncomment to not add telemetry extentions to compute VMSS
  #azhpc.add_telemetry: 0
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

  # additional variable list provided as part of the azhpc-init (comma separated without space)
  #azhpc.init_variables: variable1=value1,variable2=value2
  azhpc.init_variables: low_priority=true
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



jobs:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      find ../../ -name *.yml

- template: templates/jobs/build_cluster.yml
  parameters:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      extra_steps: ../../examples/simple_hpc_pbs/test.yml
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
