# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
# - task: AzureCLI@2
#  inputs:
#    azureSubscription: 'Microsoft Azure Internal Consumption(57a9df44-d195-45a7-9781-c6f4a1d08080)'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      az vm start -g hol-azurehpc -n headnode
#      az vmss start -g hol-azurehpc -n compute
- task: Bash@3
  inputs:
    filePath: 'libexec/azhpc-init.sh'
    arguments: ' -c examples/simple_hpc_pbs -d simple_hpc_pbs -v resource_group=hol-azurehpc2'
- task: CmdLine@2
  inputs:
    script: 'cd examples/simple_hpc_pbs ; echo $(pwd); ../../libexec/azhpc-build.sh'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd examples/simple_hpc_pbs
      echo $(pwd)
      libexec/azhpc-build.sh


    

# - task: AzureCLI@2
#  inputs:
#    azureSubscription: 'Microsoft Azure Internal Consumption(57a9df44-d195-45a7-9781-c6f4a1d08080)'
#    scriptType: 'bash'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      az vm stop -g hol-azurehpc -n headnode
#      az vmss stop -g hol-azurehpc -n compute
